apiVersion: automation.cloudbees.io/v1alpha1
kind: action
name: 'UniversalWorkflow'
description: 'The Universal Workflow'

inputs:
  CONTEXT:
    description: 'App build context'
    default: ${{ cloudbees.workspace }}
  MVN-COMPILE-ARGS:
    description: 'Maven compile arguments'
    required: false
    default: ''
  MVN-TEST-ARGS:
    description: 'Maven test arguments'
    required: false
    default: ''
  GROOVY-BUILD-ARGS:
    description: 'Groovy build arguments'
    required: false
    default: ''
  GROOVY-TEST-ARGS:
    description: 'Groovy test arguments'
    required: false
    default: ''
  SQ-PROJECT-KEY:
    description: 'SonarQube Project Key'
    required: false
    default: ''
  ARTIFACTORY-DESTINATION:
    description: ''
    required: false
    default: ''
  KANIKO-BUILD-ARGS:
    description: 'Kaniko Build Args'
    required: false
    default: ''
  KANIKO-LABELS:
    description: 'Kaniko Labels'
    required: false
    default: ''
  DOCKERFILE:
    description: 'Dockerfile name'
    required: false
    default: 'Dockerfile'
  SBATCHELDER_DOCKERHUB_TOKEN:
    required: true
    default: ''
  SONARQUBE_TOKEN:
    required: true
    default: ''
runs:
  using: composite
  steps:
    # Build Phase
    - id: code-checkout
      name: Check out repo
      kind: build
      uses: cloudbees-io/checkout@v1
      with:
        provider: ${{ cloudbees.scm.provider }}
        repository: ${{ cloudbees.scm.repository }}

    - id: ci-maven3_9
      if: ${{ inputs.MVN-COMPILE-ARGS == '' }}
      uses: sbatchelder-cba/ci-maven-3.9@v0.0.2
      with:
        context: ${{ inputs.CONTEXT }}
        mvn-compile-args: ${{ inputs.MVN-COMPILE-ARGS }}
        mvn-test-args: ${{ inputs.MVN-TEST-ARGS }}

    # custom action is evaluated before the conditional... annoying
    # - id: ci-groovy3_9
    #   if: ${{ inputs.GROOVY-BUILD-ARGS != '' }}
    #   uses: sbatchelder-cba/ci-groovy@v0.0.1
    #   with:
    #     context: ${{ inputs.CONTEXT }}
    #     groovy-build-args: ${{ inputs.GROOVY-BUILD-ARGS }}
    #     groovy-test-args: ${{ inputs.GROOVY-TEST-ARGS }}

    # Not sure if kaniko bits should live here or in the tech specific CI custom action
    # It is DRY-er if it lives here, so it is here now
    - name: Log in to OCI registry
      uses: cloudbees-io/configure-oci-credentials@v1
      with:
        registry: docker.io
        username: sbatchelder@cloudbees.com
        password: ${{ inputs.SBATCHELDER_DOCKERHUB_TOKEN }}

    # - id: kaniko
    #   uses: cloudbees-io/kaniko
    #   with:
    #       dockerfile: ${{ inputs.DOCKERFILE }}
    #       context: ${{ inputs.CONTEXT }}
    #       destination: ${{ inputs.ARTIFACTORY-DESTINATION }}
    #       build-args: ${{ inputs.KANIKO-BUILD-ARGS }}
    #       labels: ${{ inputs.KANIKO-LABELS }}

    # Analysis Phase
    - id: sonarqube
      if: ${{ inputs.SQ-PROJECT-KEY != '' }}
      uses: cloudbees-io/sonarqube@v1.0.17
      with:
        serverURL: "https://sonarqube.cb-demos.io"
        username: "admin"
        password: ${{ inputs.SONARQUBE_TOKEN }}
        language: "LANGUAGE_JAVA"

    # - name: Coverity Scan
    #   if: ${{ vars.coverityScan == true }
    #   uses: cloudbees-io/sonarqube
    #   with:
        

    # - name: Black Duck Scan
    #   if: ${{ vars.blackduckScan == true }
    #   uses: sbatchelder-cba/blackduck@v0.0.1
    #   with:
        

    # Release Build Phase


    # Deployment Build Phase
